In [10]:
#installed modules

#!pip install selenium
#driver = webdriver.Firefox(executable_path=GeckoDriverManager().install())
#!pip install webdrivermanager
#!pip install scrapy
#!pip install crochet

In [11]:
#importing python libraries and modules

#libraries & modules
import numpy as np #library for scientific computing
import pandas as pd #library for dataframes 
import warnings #library to manage warnings

from bs4 import BeautifulSoup #beautiful soup tool for scrapping
import requests #tool to request to a website

from selenium import webdriver #selenium scrapping tool
from selenium.webdriver import Firefox #firefox webdriver for selenium
from selenium.webdriver.firefox.options import Options #options for selenium webdriver
from webdriver_manager.firefox import GeckoDriverManager #gecko driver for firefox

import scrapy #scrapy tool for scraping
from scrapy.crawler import CrawlerRunner #tool to make a spider
from scrapy.http import TextResponse #tool to import text response
from crochet import setup #setup tool

warnings.filterwarnings('ignore')

### Exercici 1 (Nivell 1)
#### Realitza web scraping d'una pàgina de la borsa de Madrid (https://www.bolsamadrid.es) utilitzant BeautifulSoup i Selenium.

In [12]:
#scrapping using Beautiful Soup

#we want to scratch share prices from IBEX35
url = "https://www.bolsamadrid.es/esp/aspx/Mercados/Precios.aspx?indice=ESI100000000"
page = requests.get(url)

soup = BeautifulSoup(page.content, "html.parser")

#share prices are in a table, we use the id selection
results = soup.find(id="ctl00_Contenido_tblAcciones")

In [13]:
#from the results we take all td elements (data from table)
table_items = results.find_all("td")                                

#we make a list with elements from each column in the table
#probably this script can be improved and it is not necessary all this code 
#but at the moment, it works and I do not have time to improve it

Nombre_list = []
length = len(table_items)
i = 0
while i < length:
    Nombre_list.append(table_items[i].text.strip())
    i += 9

Ultima_list = []
length = len(table_items)
i = 1
while i < length:
    Ultima_list.append(table_items[i].text.strip())
    i += 9
    
Dif_list = []
length = len(table_items)
i = 2
while i < length:
    Dif_list.append(table_items[i].text.strip())
    i += 9
    
Max_list = []
length = len(table_items)
i = 3
while i < length:
    Max_list.append(table_items[i].text.strip())
    i += 9
    
Min_list = []
length = len(table_items)
i = 4
while i < length:
    Min_list.append(table_items[i].text.strip())
    i += 9
    
Volumen_list = []
length = len(table_items)
i = 5
while i < length:
    Volumen_list.append(table_items[i].text.strip())
    i += 9

Euro_list = []
length = len(table_items)
i = 6
while i < length:
    Euro_list.append(table_items[i].text.strip())
    i += 9    

Fecha_list = []
length = len(table_items)
i = 7
while i < length:
    Fecha_list.append(table_items[i].text.strip())
    i += 9        
    
Hora_list = []
length = len(table_items)
i = 8
while i < length:
    Hora_list.append(table_items[i].text.strip())
    i += 9    

#we make a dataframe with all columns    
columns = ['Nombre','Últ.','% Dif','Máx.','Mín',
           'Volumen','Efectivo','Fecha','Hora']
    
df = pd.DataFrame(list(zip(Nombre_list, Ultima_list, Dif_list, Max_list,
                          Min_list, Volumen_list, Euro_list, 
                          Fecha_list, Hora_list)), columns = columns)

df

,Nombre,Últ.,% Dif,Máx.,Mín,Volumen,Efectivo,Fecha,Hora
0,ACCIONA,"190,7000","1,01","193,4000","186,9000",96.746,"18.443,94",25/04/2022,Cierre
1,ACERINOX,"9,4780","-4,49","9,8700","9,4780",3.013.178,"28.912,60",25/04/2022,Cierre
2,ACS,"24,3600","-0,81","24,5700","24,0800",622.804,"15.164,75",25/04/2022,Cierre
3,AENA,"147,1000","-1,18","149,2000","145,1500",107.526,"15.846,81",25/04/2022,Cierre
4,ALMIRALL,"12,0800","1,00","12,1300","11,8300",267.166,"3.212,56",25/04/2022,Cierre
5,AMADEUS,"59,6600","0,91","60,2600","57,4400",781.828,"46.345,71",25/04/2022,Cierre
6,ARCELORMIT.,"27,0000","-8,63","28,8450","27,0000",2.224.583,"61.440,11",25/04/2022,Cierre
7,B.SANTANDER,"3,0540","-3,54","3,1525","3,0540",84.642.667,"263.070,80",25/04/2022,Cierre
8,BA.SABADELL,"0,7592","-2,74","0,7794","0,7592",24.477.285,"18.788,72",25/04/2022,Cierre
9,BANKINTER,"5,6040","0,61","5,6600","5,4240",2.770.372,"15.474,52",25/04/2022,Cierre
10,BBVA,"4,8105","-3,91","4,9425","4,8105",27.007.056,"131.498,16",25/04/2022,Cierre
11,CAIXABANK,"3,0230","-2,17","3,0750","3,0100",16.143.684,"48.966,55",25/04/2022,Cierre
12,CELLNEX,"45,4800","0,75","45,9000","44,3400",750.377,"34.069,31",25/04/2022,Cierre
13,CIE AUTOMOT.,"20,3000","-0,68","20,3800","20,0000",160.591,"3.246,50",25/04/2022,Cierre
14,ENAGAS,"20,5200","0,20","20,6300","20,3000",857.127,"17.578,60",25/04/2022,Cierre
15,ENDESA,"20,0200","0,81","20,2500","19,5050",874.098,"17.491,30",25/04/2022,Cierre
16,FERROVIAL,"24,3100","-0,65","24,5500","23,8500",822.084,"19.920,00",25/04/2022,Cierre
17,FLUIDRA,"25,2000","-3,23","25,9200","24,9600",338.024,"8.542,45",25/04/2022,Cierre
18,GRIFOLS CL.A,"17,0000","4,74","17,0000","15,9900",1.528.789,"25.485,38",25/04/2022,Cierre
19,IAG,"1,7550","-1,46","1,8055","1,7300",14.678.095,"25.985,42",25/04/2022,Cierre
20,IBERDROLA,"10,5850","1,44","10,6550","10,3400",11.997.144,"126.670,58",25/04/2022,Cierre
21,INDITEX,"20,2500","-0,34","20,3800","19,8950",4.190.699,"84.440,30",25/04/2022,Cierre
22,INDRA A,"9,2000","-0,54","9,4500","9,1000",541.770,"5.028,48",25/04/2022,Cierre
23,INM.COLONIAL,"8,1100","-0,25","8,1850","8,0150",611.266,"4.956,38",25/04/2022,Cierre
24,MAPFRE,"1,8720","-1,47","1,8930","1,8720",3.116.341,"5.856,28",25/04/2022,Cierre
25,MELIA HOTELS,"7,2300","3,36","7,3150","6,8500",1.242.292,"8.833,57",25/04/2022,Cierre
26,MERLIN,"10,8200","0,00","10,9000","10,6800",1.362.231,"14.753,42",25/04/2022,Cierre
27,NATURGY,"29,0400","1,08","29,2500","28,1700",334.782,"9.700,30",25/04/2022,Cierre
28,PHARMA MAR,"77,4600","1,52","77,4600","71,0200",61.034,"4.625,22",25/04/2022,Cierre
29,R.E.C.,"18,7050","0,81","18,7900","18,4150",940.340,"17.566,54",25/04/2022,Cierre
30,REPSOL,"12,6050","-4,47","13,0900","12,6050",9.003.008,"115.829,78",25/04/2022,Cierre
31,ROVI,"61,8500","-1,04","62,1500","61,0000",100.177,"6.191,99",25/04/2022,Cierre
32,SIEMENS GAME,"15,5700","2,70","15,6400","14,8000",1.902.236,"29.311,68",25/04/2022,Cierre
33,SOLARIA,"20,9900","-0,94","21,6600","20,7100",404.556,"8.502,57",25/04/2022,Cierre
34,TELEFONICA,"4,7980","-0,97","4,8660","4,7670",21.234.440,"102.038,80",25/04/2022,Cierre

In [14]:
#now we repeat but scrapping using Selenium

#we use this proxy because we have server rejection issues
PROXY = "11.456.448.110:8080"
firefox_options = Options()
firefox_options.add_argument('--proxy-server=%s' % PROXY)

#headless browser
firefox_options.headless = True
driver = webdriver.Firefox(options=firefox_options)

In [15]:
#url with shares prices from IBEX35
url = 'https://www.bolsamadrid.es/esp/aspx/Mercados/Precios.aspx?indice=ESI100000000'
driver.get(url)

In [16]:
#identifying elements by id and taking text
table_items = driver.find_element_by_id("ctl00_Contenido_tblAcciones").text
print(table_items)

#closing driver
driver.quit()

Nombre Últ. % Dif. Máx. Mín. Volumen Efectivo (miles €) Fecha Hora
ACCIONA 190,7000 1,01 193,4000 186,9000 96.746 18.443,94 25/04/2022 Cierre
ACERINOX 9,4780 -4,49 9,8700 9,4780 3.013.178 28.912,60 25/04/2022 Cierre
ACS 24,3600 -0,81 24,5700 24,0800 622.804 15.164,75 25/04/2022 Cierre
AENA 147,1000 -1,18 149,2000 145,1500 107.526 15.846,81 25/04/2022 Cierre
ALMIRALL 12,0800 1,00 12,1300 11,8300 267.166 3.212,56 25/04/2022 Cierre
AMADEUS 59,6600 0,91 60,2600 57,4400 781.828 46.345,71 25/04/2022 Cierre
ARCELORMIT. 27,0000 -8,63 28,8450 27,0000 2.224.583 61.440,11 25/04/2022 Cierre
B.SANTANDER 3,0540 -3,54 3,1525 3,0540 84.642.667 263.070,80 25/04/2022 Cierre
BA.SABADELL 0,7592 -2,74 0,7794 0,7592 24.477.285 18.788,72 25/04/2022 Cierre
BANKINTER 5,6040 0,61 5,6600 5,4240 2.770.372 15.474,52 25/04/2022 Cierre
BBVA 4,8105 -3,91 4,9425 4,8105 27.007.056 131.498,16 25/04/2022 Cierre
CAIXABANK 3,0230 -2,17 3,0750 3,0100 16.143.684 48.966,55 25/04/2022 Cierre
CELLNEX 45,4800 0,75 45,9000 44,3400 750.377 34.069,31 25/04/2022 Cierre
CIE AUTOMOT. 20,3000 -0,68 20,3800 20,0000 160.591 3.246,50 25/04/2022 Cierre
ENAGAS 20,5200 0,20 20,6300 20,3000 857.127 17.578,60 25/04/2022 Cierre
ENDESA 20,0200 0,81 20,2500 19,5050 874.098 17.491,30 25/04/2022 Cierre
FERROVIAL 24,3100 -0,65 24,5500 23,8500 822.084 19.920,00 25/04/2022 Cierre
FLUIDRA 25,2000 -3,23 25,9200 24,9600 338.024 8.542,45 25/04/2022 Cierre
GRIFOLS CL.A 17,0000 4,74 17,0000 15,9900 1.528.789 25.485,38 25/04/2022 Cierre
IAG 1,7550 -1,46 1,8055 1,7300 14.678.095 25.985,42 25/04/2022 Cierre
IBERDROLA 10,5850 1,44 10,6550 10,3400 11.997.144 126.670,58 25/04/2022 Cierre
INDITEX 20,2500 -0,34 20,3800 19,8950 4.190.699 84.440,30 25/04/2022 Cierre
INDRA A 9,2000 -0,54 9,4500 9,1000 541.770 5.028,48 25/04/2022 Cierre
INM.COLONIAL 8,1100 -0,25 8,1850 8,0150 611.266 4.956,38 25/04/2022 Cierre
MAPFRE 1,8720 -1,47 1,8930 1,8720 3.116.341 5.856,28 25/04/2022 Cierre
MELIA HOTELS 7,2300 3,36 7,3150 6,8500 1.242.292 8.833,57 25/04/2022 Cierre
MERLIN 10,8200 0,00 10,9000 10,6800 1.362.231 14.753,42 25/04/2022 Cierre
NATURGY 29,0400 1,08 29,2500 28,1700 334.782 9.700,30 25/04/2022 Cierre
PHARMA MAR 77,4600 1,52 77,4600 71,0200 61.034 4.625,22 25/04/2022 Cierre
R.E.C. 18,7050 0,81 18,7900 18,4150 940.340 17.566,54 25/04/2022 Cierre
REPSOL 12,6050 -4,47 13,0900 12,6050 9.003.008 115.829,78 25/04/2022 Cierre
ROVI 61,8500 -1,04 62,1500 61,0000 100.177 6.191,99 25/04/2022 Cierre
SIEMENS GAME 15,5700 2,70 15,6400 14,8000 1.902.236 29.311,68 25/04/2022 Cierre
SOLARIA 20,9900 -0,94 21,6600 20,7100 404.556 8.502,57 25/04/2022 Cierre
TELEFONICA 4,7980 -0,97 4,8660 4,7670 21.234.440 102.038,80 25/04/2022 Cierre

### Exercici 2 (Nivell 2)
#### Documenta en un word el teu conjunt de dades generat amb la informació que tenen els diferents arxius de Kaggle.

#### Title: IBEX 35 Shares Session Prices
##### Subtitle: Daily data from shares prices of most important Spanish companies. 

- Description: It shows shares of the 35 most important companies from Spain. Data is refreshed every 15 minutes.
- Licence: Open data.
- Fields description:
    - Name: Name of the company.
    - Last: It shows last share price of the company.
    - % Dif: It shows difference in percentage in relation with last value.
    - High: The high value obtaine for this share during this day.
    - Low: The low value obtained for this share during this day.
    - Volume: How many shares have been traded during this day.
    - Turnover: Stock liquidity.
    - Date: Date of data extracted.
    - Time: Time of data extracted.

### Exercici 3 (Nivell 3)
#### Tria una página web que tu vulguis i realitza web scraping mitjançant la llibreria Scrapy.

In [17]:
#we are going to scrap the same web as before
#share prices from IBEX35

setup()
url = 'https://www.bolsamadrid.es/esp/aspx/Mercados/Precios.aspx?indice=ESI100000000'
r=requests.get(url)
response = TextResponse(r.url, body=r.text, encoding='utf-8')
#print(response.text)

In [18]:
#we use xpath to identify the content we want to scrap
cells = response.xpath('//*[@id="ctl00_Contenido_tblAcciones"]/tr/td//text()').getall()
print(cells)

['ACCIONA', '190,7000', '1,01', '193,4000', '186,9000', '96.746', '18.443,94', '25/04/2022', 'Cierre', 'ACERINOX', '9,4780', '-4,49', '9,8700', '9,4780', '3.013.178', '28.912,60', '25/04/2022', 'Cierre', 'ACS', '24,3600', '-0,81', '24,5700', '24,0800', '622.804', '15.164,75', '25/04/2022', 'Cierre', 'AENA', '147,1000', '-1,18', '149,2000', '145,1500', '107.526', '15.846,81', '25/04/2022', 'Cierre', 'ALMIRALL', '12,0800', '1,00', '12,1300', '11,8300', '267.166', '3.212,56', '25/04/2022', 'Cierre', 'AMADEUS', '59,6600', '0,91', '60,2600', '57,4400', '781.828', '46.345,71', '25/04/2022', 'Cierre', 'ARCELORMIT.', '27,0000', '-8,63', '28,8450', '27,0000', '2.224.583', '61.440,11', '25/04/2022', 'Cierre', 'B.SANTANDER', '3,0540', '-3,54', '3,1525', '3,0540', '84.642.667', '263.070,80', '25/04/2022', 'Cierre', 'BA.SABADELL', '0,7592', '-2,74', '0,7794', '0,7592', '24.477.285', '18.788,72', '25/04/2022', 'Cierre', 'BANKINTER', '5,6040', '0,61', '5,6600', '5,4240', '2.770.372', '15.474,52', '25/04/2022', 'Cierre', 'BBVA', '4,8105', '-3,91', '4,9425', '4,8105', '27.007.056', '131.498,16', '25/04/2022', 'Cierre', 'CAIXABANK', '3,0230', '-2,17', '3,0750', '3,0100', '16.143.684', '48.966,55', '25/04/2022', 'Cierre', 'CELLNEX', '45,4800', '0,75', '45,9000', '44,3400', '750.377', '34.069,31', '25/04/2022', 'Cierre', 'CIE AUTOMOT.', '20,3000', '-0,68', '20,3800', '20,0000', '160.591', '3.246,50', '25/04/2022', 'Cierre', 'ENAGAS', '20,5200', '0,20', '20,6300', '20,3000', '857.127', '17.578,60', '25/04/2022', 'Cierre', 'ENDESA', '20,0200', '0,81', '20,2500', '19,5050', '874.098', '17.491,30', '25/04/2022', 'Cierre', 'FERROVIAL', '24,3100', '-0,65', '24,5500', '23,8500', '822.084', '19.920,00', '25/04/2022', 'Cierre', 'FLUIDRA', '25,2000', '-3,23', '25,9200', '24,9600', '338.024', '8.542,45', '25/04/2022', 'Cierre', 'GRIFOLS CL.A', '17,0000', '4,74', '17,0000', '15,9900', '1.528.789', '25.485,38', '25/04/2022', 'Cierre', 'IAG', '1,7550', '-1,46', '1,8055', '1,7300', '14.678.095', '25.985,42', '25/04/2022', 'Cierre', 'IBERDROLA', '10,5850', '1,44', '10,6550', '10,3400', '11.997.144', '126.670,58', '25/04/2022', 'Cierre', 'INDITEX', '20,2500', '-0,34', '20,3800', '19,8950', '4.190.699', '84.440,30', '25/04/2022', 'Cierre', 'INDRA A', '9,2000', '-0,54', '9,4500', '9,1000', '541.770', '5.028,48', '25/04/2022', 'Cierre', 'INM.COLONIAL', '8,1100', '-0,25', '8,1850', '8,0150', '611.266', '4.956,38', '25/04/2022', 'Cierre', 'MAPFRE', '1,8720', '-1,47', '1,8930', '1,8720', '3.116.341', '5.856,28', '25/04/2022', 'Cierre', 'MELIA HOTELS', '7,2300', '3,36', '7,3150', '6,8500', '1.242.292', '8.833,57', '25/04/2022', 'Cierre', 'MERLIN', '10,8200', '0,00', '10,9000', '10,6800', '1.362.231', '14.753,42', '25/04/2022', 'Cierre', 'NATURGY', '29,0400', '1,08', '29,2500', '28,1700', '334.782', '9.700,30', '25/04/2022', 'Cierre', 'PHARMA MAR', '77,4600', '1,52', '77,4600', '71,0200', '61.034', '4.625,22', '25/04/2022', 'Cierre', 'R.E.C.', '18,7050', '0,81', '18,7900', '18,4150', '940.340', '17.566,54', '25/04/2022', 'Cierre', 'REPSOL', '12,6050', '-4,47', '13,0900', '12,6050', '9.003.008', '115.829,78', '25/04/2022', 'Cierre', 'ROVI', '61,8500', '-1,04', '62,1500', '61,0000', '100.177', '6.191,99', '25/04/2022', 'Cierre', 'SIEMENS GAME', '15,5700', '2,70', '15,6400', '14,8000', '1.902.236', '29.311,68', '25/04/2022', 'Cierre', 'SOLARIA', '20,9900', '-0,94', '21,6600', '20,7100', '404.556', '8.502,57', '25/04/2022', 'Cierre', 'TELEFONICA', '4,7980', '-0,97', '4,8660', '4,7670', '21.234.440', '102.038,80', '25/04/2022', 'Cierre']